-- MySQL Script generated by MySQL Workbench
-- Sun 07 Nov 2021 10:00:16 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema excalibur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema excalibur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `excalibur` DEFAULT CHARACTER SET utf8 ;
USE `excalibur` ;

-- -----------------------------------------------------
-- Table `excalibur`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excalibur`.`publisher` (
  `idpublisher` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idpublisher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excalibur`.`videogame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excalibur`.`videogame` (
  `idvideogame` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `release` VARCHAR(45) NULL,
  `publisher_idpublisher` INT NOT NULL,
  PRIMARY KEY (`idvideogame`),
  INDEX `fk_videogame_publisher_idx` (`publisher_idpublisher` ASC) VISIBLE,
  CONSTRAINT `fk_videogame_publisher`
    FOREIGN KEY (`publisher_idpublisher`)
    REFERENCES `excalibur`.`publisher` (`idpublisher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excalibur`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excalibur`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excalibur`.`videogame_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excalibur`.`videogame_has_genre` (
  `videogame_idvideogame` INT NOT NULL,
  `genre_idgenre` INT NOT NULL,
  PRIMARY KEY (`videogame_idvideogame`, `genre_idgenre`),
  INDEX `fk_videogame_has_genre_genre1_idx` (`genre_idgenre` ASC) VISIBLE,
  INDEX `fk_videogame_has_genre_videogame1_idx` (`videogame_idvideogame` ASC) VISIBLE,
  CONSTRAINT `fk_videogame_has_genre_videogame1`
    FOREIGN KEY (`videogame_idvideogame`)
    REFERENCES `excalibur`.`videogame` (`idvideogame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videogame_has_genre_genre1`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `excalibur`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
